### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by rayanmishra** [luxury-cruise-tour/luxuryCruiseTour#8]
AWESOME ! I spent all my money and booked the tours. Great Job!! 

Following are some issues that could be solved :
1. Refresh is not working in routing (we have the same issue though)

2. Tour text titles have a hover issue at the bottom of the book the tour page. When we hover over the "Book This Tour" link, the text disappears. This is probably because the link container is taking up the entire space (pun intended).

3. Book a Tour - Dates section:
a. Put a maximum limit on the rooms, maybe (we have booked 92 rooms).
b. The room buttons are not in the same line as "Adult" and "Children".(CSS)
c. "Stays," "Cruises," and "Attractions" seem like clickable links but serve no purpose, confusing the user as the cursor becomes a pointer.

4. The images can be compressed to optimize the speed of page reloads.

**Comment by OsmanAOmar** [comment]
Changed code based off feedback.
1. Added _redirect into public folder, based off Netlify manual
2. General CSS styling
3. Add logic to disable property to restrict bookings
4. Added a loading dialect in case it's needed
